### ISSUE TITLE
Exception message causes Scheduler to crash

### ISSUE THREAD

**Issue by hbpe-aarhus** [itk-dev-rpa/OpenOrchestrator#102]
A process failing with the following log message

```
Log ID:
f8942578-e6c5-4c61-b1ba-d4e19eadb925
Log Time:
06-11-2024 11:12:22
Process Name:
MBA_Kørselskontoret_Skolelister_SikkerPost
Log Level:
Error
Message:
Process Error #1: Exception("Failed to find and click button '{'Name': 'Send Digitalt'}' after 3 attempts.")

Trace:
Traceback (most recent call last):
  File "C:\Users\SvcRpaMBA001\Desktop\Scheduler_Repos\dd924713-98f8-4997-925b-d01a86a70e3a\robot_framework\queue_framework.py", line 41, in main
    process.process(orchestrator_connection, queue_element)
  File "C:\Users\SvcRpaMBA001\Desktop\Scheduler_Repos\dd924713-98f8-4997-925b-d01a86a70e3a\robot_framework\process.py", line 154, in process
    _click_button_with_retry(orchestrator_connection, outlook_mail_window, max_attempts=3, Name='Send Digitalt')
  File "C:\Users\SvcRpaMBA001\Desktop\Scheduler_Repos\dd924713-98f8-4997-925b-d01a86a70e3a\robot_framework\process.py", line 39, in _click_button_with_retry
    raise Exception(f"Failed to find and click button '{kwargs}' after {max_attempts} attempts.")  # pylint: disable=broad-exception-raised
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Exception: Failed to find and click button '{'Name': 'Send Digitalt'}' after 3 attempts.
```

causes Scheduler to crash with this message

```
Log ID:
9946eb05-e7c6-488b-88f5-42f8953b94bf
Log Time:
06-11-2024 11:35:35
Process Name:
MBA_Kørselskontoret_Skolelister_SikkerPost
Log Level:
Error
Message:
Uncaught Exception:
Type: 
Value: (pyodbc.ProgrammingError) ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Strengdata eller binære data afkortes i tabel \'BAIT-DF-OO.dbo.Queues\', kolonne \'message\'. Afkortet værdi: \'Process Error #1: Exception("Failed to find and click button \'\'{\'\'Name\'\': \'\'Send Digitalt\'\'}\'\' after\'. (2628) (SQLExecDirectW); [42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Sætningen blev afsluttet. (3621)')
[SQL: UPDATE [Queues] SET status=?, end_date=?, message=? WHERE [Queues].id = ?]
[parameters: ('FAILED', datetime.datetime(2024, 11, 6, 11, 35, 35, 141491), 'Process Error #1: Exception("Failed to find and click button \'{\'Name\': \'Send Digitalt\'}\' after 3 attempts.")\n\nTrace:\nTraceback (most recent  ... (846 characters truncated) ... ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nException: Failed to find and click button \'{\'Name\': \'Send Digitalt\'}\' after 3 attempts.\n', UUID('a67921c0-c0ec-428f-8d4f-43647f59d518'))]
(Background on this error at: https://sqlalche.me/e/20/f405)
Trace: 
```

Might be the backslashes and/or single quotes present in the exception message being the root cause.

Running OpenOrchestrator 1.3.0.

**Comment by hbpe-aarhus** [comment]
Tried removing the logging of kwargs but I still get the error:

```
Log ID:
ae03ada2-fb60-4920-8854-72b7b640c796
Log Time:
06-11-2024 11:55:34
Process Name:
MBA_Kørselskontoret_Skolelister_SikkerPost
Log Level:
Error
Message:
Process Error #1: Exception('Failed to find and click button after 3 attempts.')

Trace:
Traceback (most recent call last):
  File "C:\Users\SvcRpaMBA001\Desktop\Scheduler_Repos\827fe8e0-0801-4ece-8588-29773e6b356f\robot_framework\queue_framework.py", line 41, in main
    process.process(orchestrator_connection, queue_element)
  File "C:\Users\SvcRpaMBA001\Desktop\Scheduler_Repos\827fe8e0-0801-4ece-8588-29773e6b356f\robot_framework\process.py", line 154, in process
    _click_button_with_retry(orchestrator_connection, outlook_mail_window, max_attempts=3, Name='Send Digitalt')
  File "C:\Users\SvcRpaMBA001\Desktop\Scheduler_Repos\827fe8e0-0801-4ece-8588-29773e6b356f\robot_framework\process.py", line 39, in _click_button_with_retry
    raise Exception(f"Failed to find and click button after {max_attempts} attempts.")  # pylint: disable=broad-exception-raised
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Exception: Failed to find and click button after 3 attempts.
```

and

```
Log ID:
8dfc3c4b-a974-4d33-a885-016155c332fe
Log Time:
06-11-2024 11:55:34
Process Name:
MBA_Kørselskontoret_Skolelister_SikkerPost
Log Level:
Error
Message:
Uncaught Exception:
Type: 
Value: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Strengdata eller binære data afkortes i tabel 'BAIT-DF-OO.dbo.Queues', kolonne 'message'. Afkortet værdi: 'Process Error #1: Exception(''Failed to find and click button after 3 attempts.'')\n\nTrace:\nTraceback'. (2628) (SQLExecDirectW); [42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Sætningen blev afsluttet. (3621)")
[SQL: UPDATE [Queues] SET status=?, end_date=?, message=? WHERE [Queues].id = ?]
[parameters: ('FAILED', datetime.datetime(2024, 11, 6, 11, 55, 34, 943460), 'Process Error #1: Exception(\'Failed to find and click button after 3 attempts.\')\n\nTrace:\nTraceback (most recent call last):\n  File "C:\\Users\\ ... (756 characters truncated) ...    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nException: Failed to find and click button after 3 attempts.\n', UUID('406369b8-f244-4105-be62-ed506f10ad46'))]
(Background on this error at: https://sqlalche.me/e/20/f405)
Trace: 
```

@ghbm-itk  Are you not supposed to raise exceptions in the process-part of Robot Framework like below?

```py
def _click_button_with_retry(orchestrator_connection: OrchestratorConnection, window, max_attempts=10, **kwargs):
    for attempt in range(max_attempts):
        try:
            window.ButtonControl(**kwargs).GetInvokePattern().Invoke()
            orchestrator_connection.log_trace(f"Button found and clicked.")
            return
        except Exception:  # pylint: disable=broad-exception-caught
            orchestrator_connection.log_trace(f"Button not found and clicked (attempt {attempt + 1}/{max_attempts}). Retrying...")
            time.sleep(10)
    raise Exception(f"Failed to find and click button after {max_attempts} attempts.")  # pylint: disable=broad-exception-raised
```

**Comment by ghbm-itk** [comment]
> Might be the backslashes and/or single quotes present in the exception message being the root cause

This is 100% not the case. All queries are parameterized and are not affected by the input.

> Strengdata eller binære data afkortes i tabel 'BAIT-DF-OO.dbo.Queues', kolonne 'message'.

What is happening is that it looks like you're trying to write 1200 characters to an SQL column that's only defined to hold 1000 chars. 

Does Scheduler crash from this? That I don't udnerstand

**Comment by ghbm-itk** [comment]
We already implemented a fix when logs in the logging table where to big, but we don't have anything like that on queue elements

**Comment by hbpe-aarhus** [comment]
Ah, that makes sense, then.

Is there any suggested workaround to use for now?

**Comment by ghbm-itk** [comment]
In the robot framework in 'exeptions.py' on line 33 you can remove the error message from being added to the queue element's message. Alternatively truncate the message.

can you confirm that this error causes Sheduler to crash? Or is it just the robot that crashes?

**Comment by hbpe-aarhus** [comment]
> In the robot framework in 'exeptions.py' on line 33 you can remove the error message from being added to the queue element's message. Alternatively truncate the message.

Cheers, I'll have a look at those suggestions.

>can you confirm that this error causes Sheduler to crash? Or is it just the robot that crashes?

Good question to ask. It's actually just the robot. Scheduler can pickup other Triggers just fine if the above error occurs.

**Comment by hbpe-aarhus** [comment]
I tried truncating error_msg, but the robot still crashes

```py
from OpenOrchestrator.database import truncated_string
```

```py
    if queue_element:
        truncated_error_msg = truncated_string.truncate_message(error_msg) # error_msg truncated here
        orchestrator_connection.set_queue_element_status(queue_element.id, QueueStatus.FAILED, truncated_error_msg)
    error_screenshot.send_error_screenshot(error_email, error, orchestrator_connection.process_name)
```

**Comment by ghbm-itk** [comment]
truncate_message defaults to a length of 8000 characters
