### ISSUE TITLE
Editing triggers don't work in SQLite

### ISSUE THREAD

**Issue by hbpe-aarhus** [itk-dev-rpa/OpenOrchestrator#44]
Currently it does not seem possible to edit a trigger after it has been created. Enabling the option to edit a trigger after creation would be an obvious benefit.

**Comment by ghbm-itk** [comment]
Triggers can be edited by double clicking

**Comment by hbpe-aarhus** [comment]
Using SQLite, I get the error below when double-clicking a trigger.

Running Windows 10 and using the connection string "sqlite:///C:\\OpenOrchestratorDB\\test_database.db"

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\AZ41832\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1814, in _execute_context
    context = constructor(
              ^^^^^^^^^^^^
  File "C:\Users\AZ41832\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\default.py", line 1455, in _init_compiled
    l_param: List[Any] = [
                         ^
  File "C:\Users\AZ41832\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\default.py", line 1456, in <listcomp>
    flattened_processors[key](compiled_params[key])
  File "C:\Users\AZ41832\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\sql\sqltypes.py", line 3651, in process
    value = value.hex
            ^^^^^^^^^
AttributeError: 'str' object has no attribute 'hex'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\AZ41832\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\AZ41832\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenOrchestrator\orchestrator\trigger_tab.py", line 83, in <lambda>
    si_table.bind('<Double-1>', lambda e: double_click_trigger_tables(sc_table, q_table, si_table))
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AZ41832\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenOrchestrator\orchestrator\trigger_tab.py", line 224, in double_click_trigger_tables
    trigger = get_selected_trigger(sc_table, q_table, si_table)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AZ41832\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenOrchestrator\orchestrator\trigger_tab.py", line 212, in get_selected_trigger
    return db_util.get_trigger(trigger_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AZ41832\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenOrchestrator\database\db_util.py", line 56, in inner
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AZ41832\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenOrchestrator\database\db_util.py", line 101, in get_trigger
    return session.scalar(query)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AZ41832\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\session.py", line 2358, in scalar
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AZ41832\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\session.py", line 2190, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AZ41832\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\context.py", line 293, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "C:\Users\AZ41832\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "C:\Users\AZ41832\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\sql\elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AZ41832\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1639, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AZ41832\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1820, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\AZ41832\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 2343, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\AZ41832\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1814, in _execute_context
    context = constructor(
              ^^^^^^^^^^^^
  File "C:\Users\AZ41832\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\default.py", line 1455, in _init_compiled
    l_param: List[Any] = [
                         ^
  File "C:\Users\AZ41832\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\default.py", line 1456, in <listcomp>
    flattened_processors[key](compiled_params[key])
  File "C:\Users\AZ41832\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\sql\sqltypes.py", line 3651, in process
    value = value.hex
            ^^^^^^^^^
sqlalchemy.exc.StatementError: (builtins.AttributeError) 'str' object has no attribute 'hex'
[SQL: SELECT "Triggers".id, "Triggers".trigger_name, "Triggers".process_name, "Triggers".last_run, "Triggers".process_path, "Triggers".process_args, "Triggers".process_status, "Triggers".is_git_repo, "Triggers".is_blocking, "Triggers".type
FROM "Triggers"
WHERE "Triggers".id = ?]
[parameters: [{}]]

**Comment by ghbm-itk** [comment]
Hmm seems that SQLite and OpenOrchestrator doesn't work as well as I hoped...

**Comment by ghbm-itk** [comment]
https://github.com/itk-dev-rpa/OpenOrchestrator/issues/75
