### ISSUE TITLE
(Bug) Failed scheduled trigger blocks subsequent runs

### ISSUE THREAD

**Issue by hbpe-aarhus** [itk-dev-rpa/OpenOrchestrator#95]
Yesterday we experienced the below error due to some issues with SMTP. The scheduled trigger is set to run at 10:05 on all working days.

Today the trigger did not run because yesterday's run failed.

Is this by design? In my mind, a scheduled trigger should not be blocked from subsequent runs if a single run fails.

***

**Log _ID:**

149b41bd-4be1-4126-befe-b53efb6429bc

**Log Time:**

10-07-2024 10:05:42

**Process Name:**

MBA_Kørselskontoret_Skolelister

**Log Level:**

Error

**Message:**

An uncaught error ocurred during the process:

[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: C:\Users\SvcRpaMBA001\Desktop\Scheduler_Repos\78bba107-672f-484c-bffe-0276f4818873\.venv\Scripts\python.exe -m pip install --upgrade pip
2024-07-10 10:05:41.159 | INFO     | __main__:main:149 - Process started
2024-07-10 10:05:41.159 | INFO     | __main__:main:155 - Getting data from SQL Server
2024-07-10 10:05:41.866 | INFO     | __main__:main:160 - Writing file Vorrevangskolen-20240205.xlsx
2024-07-10 10:05:41.929 | INFO     | __main__:main:163 - Sending email
Traceback (most recent call last):
  File "C:\Users\SvcRpaMBA001\Desktop\Scheduler_Repos\78bba107-672f-484c-bffe-0276f4818873\skolelister.py", line 176, in 
    main()
  File "C:\Users\SvcRpaMBA001\Desktop\Scheduler_Repos\78bba107-672f-484c-bffe-0276f4818873\skolelister.py", line 164, in main
    _send_mail(skole, dato, excel_filename)
  File "C:\Users\SvcRpaMBA001\Desktop\Scheduler_Repos\78bba107-672f-484c-bffe-0276f4818873\skolelister.py", line 103, in _send_mail
    smtp.starttls()
  File "C:\Users\SvcRpaMBA001\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 771, in starttls
    raise SMTPNotSupportedError(
smtplib.SMTPNotSupportedError: STARTTLS extension not supported by server.
Traceback (most recent call last):
  File "C:\Users\SvcRpaMBA001\Desktop\Scheduler_Repos\78bba107-672f-484c-bffe-0276f4818873\main.py", line 20, in 
    subprocess.run(command_args, check=True)
  File "C:\Users\SvcRpaMBA001\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['.venv\\Scripts\\python', 'skolelister.py', 'MBA_Kørselskontoret_Skolelister', 'mssql+pyodbc://srvsqlhotel03/BAIT-DF-OO?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes', 'ElrVGDLKUIz_tlJcbaBIy0SU0wdRjq1eap9uximRyNI=', '']' returned non-zero exit status 1.`

**Comment by ghbm-itk** [comment]
This is by design.
It prevents a failing robot from repeating its errors before someone has had a chance to look at it
